import{a as v,S,i as n}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="50600363-124150c1580125848cace6785",B="https://pixabay.com/api/",P=15;async function u(r,t){const s={key:q,q:r,page:t,per_page:P,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await v.get(B,{params:s})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".load-more"),h=document.getElementById("loader"),E=new S(".gallery a");function f(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:i,comments:b,downloads:w})=>`<li class = 'gallery-item'>
<a href = "${a}">
    <img src = "${s}" alt = "${e}"/>
    </a>
    <div class="info">
    <p><b>Likes:</b>${o}</p>
    <p><b>Views:</b>${i}</p>
    <p><b>Comments:</b>${b}</p>
    <p><b>Downloads:</b>${w}</p>
    </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",t),E.refresh()}function $(){m.innerHTML=""}function p(){h.classList.remove("is-hidden")}function y(){h.classList.add("is-hidden")}function M(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}const A=document.querySelector(".form"),I=document.querySelector(".load-more");let c="",l=1,d=0;A.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements["search-text"].value.trim(),l=1,!c){n.Toast.warning({message:"Please enter a search query.",position:"topRight"});return}$(),L(),p();try{const t=await u(c,l);if(d=t.totalHits,t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}f(t.hits),d>15&&M()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});I.addEventListener("click",async()=>{l+=1,p();try{const r=await u(c,l);f(r.hits);const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=d&&(L(),n.error({message:"We are sorry, but you have reached the end of search results."}))}catch{n.error({message:"Failed to load more images."})}finally{y()}});
//# sourceMappingURL=index.js.map
